name: Windows Unit Test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.30.x"

      - name: Use cmake
        run: cmake --version

      - name: Install Make
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
      - shell: msys2 {0}
        run: |
          pacman -Syu --noconfirm make

      - name: Build and run tests with default settings
        run: |
          cd Game\app
          make build

      - name: Build and run tests with SSE4.1 optimization
        run: |
          cd Game\app
          make build_sse4.1

      - name: Allow PR if tests succeed
        if: success()
        run: echo "√ Tests passed, PR is ready for review."

      - name: Fail the PR if tests fail
        if: failure()
        run: echo "x Tests failed, please fix them before proceeding with the PR."
